#mongodbdata:
#    image: mongo:2.6
#    volumes:
#        - /data/db
#    restart: "no"
#    command: /bin/echo "Data-only container for mongodb."

#mongodb:
#    image: mongo:2.6
#    volumes_from:
#        - mongodbdata
#    expose:
#        - "27017"
#    command: --smallfiles

mongodb:
    image: mongo:2.6

    # Port mapping: allow only access on local docker host
    ports:
      - "127.0.0.1:27017:27017"
    expose:
      - "27017"

    # Use storage on host file system
    volumes:
      - /var/lib/mongodb_docker:/data/db
    command: --smallfiles

    # restart: always

orion:
    image: geonovum/orionrush
    links:
        - mongodb
    ports:
        - "1026:1026"

sthcomet:
    image: geonovum/sthcomet
    log_driver: "syslog"
    links:
        - mongodb
        - orion
    ports:
        - "8666:8666"

iotacpp:
    image: telefonicaiot/iotacpp
    links:
        - mongodb
        - orion
    ports:
        - "185.21.189.59:8000:8080"
        - "185.21.189.59:8081:8081"
        - "185.21.189.59:1883:1883"
